### ISSUE TITLE
Not working, got red screen

### ISSUE THREAD

**Issue by b4d4** [johnuberbacher/flutter_medical#2]
Flutter version: 1.20.4
SO: W10 x64

Got this trace: 
`I/flutter (28331): The following NoSuchMethodError was thrown building HomeScreen(dirty, dependencies: [MediaQuery],
I/flutter (28331): state: _HomeScreenState#1c7c2):
I/flutter (28331): The getter 'length' was called on null.
I/flutter (28331): Receiver: null
I/flutter (28331): Tried calling: length
I/flutter (28331):
I/flutter (28331): The relevant error-causing widget was:
I/flutter (28331):   HomeScreen
I/flutter (28331):   file:///E:/bada/Documents/FAUSI/FLUTTER/OCTUBRE%202020/Flutter_medical/lib/main.dart:64:30
I/flutter (28331):
I/flutter (28331): When the exception was thrown, this was the stack:
I/flutter (28331): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (28331): #1      titleCase (package:flutter_medical/widgets.dart:369:12)
I/flutter (28331): #2      _HomeScreenState.build (package:flutter_medical/routes/home.dart:415:50)
I/flutter (28331): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
I/flutter (28331): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
I/flutter (28331): #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (28331): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (28331): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
I/flutter (28331): #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
I/flutter (28331): #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
I/flutter (28331): #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (28331): #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (28331): #12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter (28331): #16     _invoke (dart:ui/hooks.dart:251:10)
I/flutter (28331): #17     _drawFrame (dart:ui/hooks.dart:209:3)
I/flutter (28331): (elided 3 frames from dart:async)
I/flutter (28331):
I/flutter (28331): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (28331): Instance of 'QuerySnapshot'
I/flutter (28331): worked
I/flutter (28331): Instance of 'QuerySnapshot'
I/flutter (28331): Instance of 'QuerySnapshot'
I/flutter (28331): Another exception was thrown: NoSuchMethodError: The getter 'length' was called on null.`

**Comment by saad0259** [comment]
@b4d4  found any solution?
